urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription')
]

templates/patient/appointment.html
{% extends 'patient/patient_home.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<span class="text-white">Book your Seat</span>
					<h1 class="text-capitalize mb-5 text-lg">Appoinment</h1>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="appoinment section">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="mt-3">
					<div class="feature-icon mb-3">
						<i class="icofont-support text-lg"></i>
					</div>
					<span class="h3">Call for an Emergency Service!</span>
					<h2 class="text-color mt-3">+84 789 1256 </h2>
				</div>
			</div>

			<div class="col-lg-8">
				<div class="appoinment-wrap mt-5 mt-lg-0 pl-lg-5">
					<h2 class="mb-2 title-color">Book an appoinment</h2>
					<p class="mb-4"> make your booking.</p>
					<form id="#" class="appoinment-form" method="POST" action="#">
						<div class="row">
							<div class="col-lg-6">
								<div class="form-group">
									<select class="form-control" id="exampleFormControlSelect1">
										<option>select department</option>
										<option>Heart Centre</option>
										<option>Neuro Science</option>
										<option>Liver and gastro science</option>
										<option>Women Care</option>
										<option>Child Care</option>
										<option> orthopaedics</option>
										<option> Renal Care</option>
										<option> pulmonology</option>
										<option> Endocrine sciences</option>
										<option> opthalmology</option>
										<option>Dental Care</option>
										<option> Surgical oncology</option>
										<option> psycyhiatry </option>
										<option> Anaesthesiology</option>
										<option> Dermatology</option>
										<option> Radiology</option>
									</select>

								</div>
							</div>
							<div class="col-lg-6">
								<div class="form-group">
									<select class="form-control" id="exampleFormControlSelect2">
										<option>Select Doctors</option>
										<option>Software Design</option>
										<option>Development cycle</option>
										<option>Software Development</option>
										<option>Maintenance</option>
										<option>Process Query</option>
										<option>Cost and Duration</option>
										<option>Modal Delivery</option>
									</select>
								</div>
							</div>

							<div class="col-lg-6">
								<div class="form-group">
									<input name="date" id="date" type="text" class="form-control"
										placeholder="dd/mm/yyyy">
								</div>
							</div>

							<div class="col-lg-6">
								<div class="form-group">
									<input name="mob" id="mob" type="text" class="form-control"
										placeholder="Mobile Number">
								</div>
							</div>
							<div class="col-lg-6">
								<div class="form-group">
									<input name="name" id="name" type="text" class="form-control"
										placeholder="First Name">
								</div>
							</div>

							<div class="col-lg-6">
								<div class="form-group">
									<input name="name" id="name" type="text" class="form-control"
										placeholder="Last Name">
								</div>
							</div>
						</div>
						<div class="form-group-2 mb-4">
							<textarea name="message" id="message" class="form-control" rows="6"
								placeholder="Your Message"></textarea>
						</div>

						<a class="btn btn-main btn-round-full" href="{% url 'patient:confirm' %}">Make Appoinment<i
								class="icofont-simple-right ml-2"></i></a>
					</form>
				</div>
			</div>
		</div>
	</div>
	</div>
</section>

{% endblock %}

templates/patient/appt_1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book an Appointment</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>

    <!-- Select Box  -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />


    <!-- Home icon  -->
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    
  

    <link rel="stylesheet" href="{% static 'css/appt_1.css' %}">

    {% block header %}
    <style>
        #btn_next{
            display: none;
        }
    </style>

    {% endblock %}

</head>

<body>

    <div class="container-fluid">

        <!-- header container -->
        <div class="row" id="header_container">
            <div class="col-11">
                <h1>BOOK APPOINTMENT</h1>
            </div>
            {% if 'patient' in request.session %}
            <div class="col-1 mt-3">
                <a href="{% url 'patient:home' %}"><i class="fa fa-home" style="font-size:48px;color:white"></i></a>
            </div>
            {% else %}
            <div class="col-1 mt-3">
                <a href="{% url 'staff:staff_home' %}"><i class="fa fa-home" style="font-size:48px;color:white"></i></a>
            </div>
            {% endif %}
        </div>
        <!-- header container end-->

        {% block content %}

        <!-- bg-image container -->
        <div class="row" id="image">
            <div class="col-12">

            </div>
        </div>
        <!-- bg-image container end-->


        <!-- select container -->
        <form method="POST">
            {% csrf_token %}
            <input type="hidden"   name="selected_doctor" id="selected_doctor">
            <div class="row select_tab" id="select_container">

                <div class="col-3 s-1"></div>
                <div class="col-3 s-2">
                    <div>
                        <select name="department" id="department">
                            <option disabled selected >Select Department</option>

                            {% for dept in departments %}
                            <option value="{{ dept.id }}">{{ dept.department | title }}</option>
                             {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-3 s-3">
                    <div>
                        <select name="doctor" id = "doctor">
                             
                             
                        </select>
                    </div>
                </div>
                <div class="col-3 s-4"></div>

            </div>
            <!-- row end  -->


            <div class="row next">
                <div class="col-5 n-1"></div>
                <div class="col-2 n-2">
                    <button type="button" id="btn_next"  class="btn btn-primary nxt">NEXT</button>
                </div>
                <div class="col-5 n-3"></div>
            </div>
        </form>
        <!-- select container end-->

        {% endblock %}

    </div>
 
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
 

    <script>
    
      var selected_doctor_id;

        $('#department').change(function(){

             id = $(this).val()
             $.ajaxSetup({
            headers: {
              "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })

             $.ajax({

                url : "{% url 'patient:get_doctors' %}",  
                type : 'POST',
                data : {
                    id : id
                },

                success : function(response){

                    $('#doctor').empty()
                    $('#doctor').append('<option selected disabled> Select Doctor </option>')
                    for(var i = 0; i< response.doctors.length; i++){

                        
                        $('#doctor').append('<option value = '+response.doctors[i].dr_id + '>'+ response.doctors[i].dr_name.toUpperCase() + ' </option>' )
                    
                        
                    }
                }


             })
        })

        $('#doctor').change(function(){
            let id = $(this).val()
            selected_doctor_id = id
            $('#selected_doctor').val(id)
        })


        $('button').click(function(){

            window.location.href = "{% url 'patient:appointment_2' %}?dr=" + selected_doctor_id
        })
    </script>

    <script>
      $('select').change(function(){
console.log('dep',$('#department').val())
console.log('doc',$('#doctor').val())

        // alert($('#department').val() != 'Select Department' && $('#doctor').val() != 'Select Doctor' )
       
        if(($('#department').val() != null) &&($('#doctor').val() != null) ){

            $('#btn_next').show()
            console.log('yes')
        }
        else{
            $('#btn_next').hide()
            console.log('no')
        }

      })
    </script>

</body>

</html>

templates/patient/appt_4.html
{% extends 'patient/appt_1.html' %}
{% load static %}

{% block header %}


<link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

<link rel="stylesheet" href="//fonts.googleappis.com/css?family=Roboto:300,400,500,700|Material+Icons">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="{% static 'css/appt_4.css' %}">
{% endblock %}


{% block content %}

<!-- row start  -->
<div class="row d-flex h-100 booking">

    <section class="section confirmation">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-8">
                    <div class="confirmation-content text-center">

                        <i class="fa fa-check" style="font-size:48px;color:green"></i>
                        <i class="icofont-check-circled text-lg text-color-2"></i>
                        <h2 class="mt-3 mb-4" style="color: green;">Your booking has been successfully initiated</h2>
                        <p>You will receive an SMS confirmation shortly. On the day of appointment, please reach the
                            hospital </p>
                        <p>atleast 30 minutes before your appointment time.</p>
                        <p><b> Booking details are shown below: </b></p>                  

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-4"></div>
                <div class="col-4">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="d-flex text-black">
                                <div class="flex-shrink-0">
                                    <img src="https://care.bestdocapp.com/_nuxt/img/male_doctor.7fec7ec.svg"
                                        alt="Generic placeholder image" class="img-fluid"
                                        style="width: 80px; height: 80px; border-radius: 10px;" />
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <h5 class="mt-4 mb-1 text-uppercase">{{ doctor_name | title }}</h5>
                                    <p class="mb-2 pb-1 text-uppercase" style="color: #2b2a2a;">
                                        {{ dep | upper}}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4"></div>
            </div>

            <div class="row mb-4">
                <div class="col-4">
                    <div class="card time mt-4 ml-3">
                        <div class="card-body p-4">
                            <div class="v-card">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="feather feather-activity">
                                    <circle cx="12" cy="12" r="10"></circle>
                                    <polyline points="12 6 12 12 15 15"></polyline>
                                </svg>
                                <span class="body-1">{{ booking_date }}</span> <br>
                                <span class="title"><b>{{ booking_time }}</b> </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card ref mt-4">
                        <div class="card-body p-4">
                            <div class="v-card">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="feather feather-activity">
                                    <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                    <line x1="16" y1="2" x2="16" y2="6"></line>
                                    <line x1="8" y1="2" x2="8" y2="6"></line>
                                    <line x1="3" y1="10" x2="21" y2="10"></line>
                                </svg>
                                <span class="body-1">Ref No</span> <br>
                                <span class="title"><b>{{reference_no}}</b> </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-12">
                    <a href="{% url 'patient:appointment_1' %}" class="btn btn-primary">BOOK ANOTHER APPOINTMENT</a>                    
                </div>
            </div>

        </div>
    </section>
</div>
<!-- row end  -->





{% endblock %}

templates/patient/booking_partial.html
{% if booking_records %}
<table class="table table-primary table-striped">
    <tr>
        <th>Sl No</th>
        <th> Reference No</th>
        <th>Patient Name</th>
        <th> Doctor </th>
        <th> Date </th>
        <th> Time </th>
        <th> Status </th>

        <th> Action </th>

    </tr>
    {% for record in booking_records %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ record.reference_no }}</td>
        <td> {{ record.patient_name | title }} </td>
        <td> {{ record.doctor.doctor_name | title }} </td>
        <td> {{ record.booking_date }} </td>
        <td> {{ record.time }} </td>

        <td> {{ record.status }}</td>
        {% if record.status == 'booked' %}
        <td> <a href="{% url 'patient:cancel_booking' record.id %}" class="btn btn-danger"> Cancel </a> </td>


        {% endif %}

        {% if record.status == 'completed' %}
        <td><button type="button" class="btn btn-primary" value="{{ record.id}}" data-bs-toggle="modal" 
            data-bs-target="#exampleModal" onclick="get_pre(this.value)">
            Prescription</button></td>

       {% endif %}


    </tr>

    {% endfor %}



</table>

{% else %}

<h2> No Records Found</h2>

{% endif %}

templates/patient/confirmation.html
{% extends 'patient/patient_home.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="section confirmation">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-8">
				<div class="confirmation-content text-center">
					<i class="icofont-check-circled text-lg text-color-2"></i>
					<h2 class="mt-3 mb-4">Your Password has changed </h2>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

templates/patient/my_bookings.html
{% extends 'patient/patient_master.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}


<h1 style="color: rgb(6, 6, 165); text-align: center;">
    Appointment List
  </h1>
  
  <section class="appoinment section">
      <div class="container">
        <div class="row">
          {% include 'patient/booking_partial.html' %}
        </div>
      </div>

    </section>

    

{% endblock %}

templates/patient/patient_home.html
{% extends 'patient/patient_master.html' %} 
{% load static %} 

{% block header %}

<link rel="stylesheet" href="{% static 'css/pt_home.css' %}" />

<style>
     

</style>

{% endblock %} 

{% block content %}



<h1 style="color: rgb(6, 6, 165); margin-top: 50px; text-align: center;"
  class="mb-4">
  Welcome  {{ patient_name | title }}
</h1>

  
  <div class="card-category-5">
  
	<ul class="all-pr-cards">
	   <li>
        <div class="per-card-3" style="height: 320px;">
            <div class="card-image">
                <span></span>
                <img src="{% static 'assets/img/calendar.png' %}" height="200px" class="logo" />
              </div>
            <div class="card-body">
              <h5 class="card-title">Last Appointment</h5>
              <p class="card-text"> Reference No : {{last_booking.0.reference_no }}</p>
              <p class="card-text"> Booking Date : {{last_booking.0.booking_date }}</p>
              <p class="card-text"> Time : {{last_booking.0.time }} </p>
              <p class="card-text"> Status : {{last_booking.0.status }} </p>
               
            </div>
          </div>
       </li>
  
	  
       <li>
        <a href="{% url 'patient:booking_history' %}">
        <div class="per-card-3" style="height: 320px;">
            <div class="card-image">
                <span></span>
                <img src="{% static 'assets/img/calendar.png' %}" height="200px" class="logo" />
              </div>
            <div class="card-body">
              <h5 class="card-title">My Bookings</h5>
              <p class="card-text"> Total Bookings : {{ booking }}</p>
              <p class="card-text"> Cancelled Bookings : {{ cancelled_count }} </p>
              
               
            </div>
          </div>
        </a>
       </li>
	</ul>
  </div>


{% endblock %}

<!-- <script>
		// Get the modal
		var modal = document.getElementById("myModal");

		// Get the button that opens the modal
		var btn = document.getElementById("myBtn");

		// Get the <span> element that closes the modal
		var span = document.getElementsByClassName("close")[0];

		// When the user clicks the button, open the modal 
		btn.onclick = function () {
			modal.style.display = "block";
		}

		// When the user clicks on <span> (x), close the modal
		span.onclick = function () {
			modal.style.display = "none";
		}

		// When the user clicks anywhere outside of the modal, close it
		window.onclick = function (event) {
			if (event.target == modal) {
				modal.style.display = "none";
			}
		}
	</script> -->

templates/patient/pt_edit_profile.html
{% extends 'patient/patient_home.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href=" {% static 'css/pt_edit_prof.css' %}">
{% endblock %}

{% block content %}

<section class="edit_section">

    <div class="container">

        <div class="main-body">
            <div class="row mt-1 mb-2 ">
                <div class="col-2"></div>
                <div class="col-8">

                </div>
                <div class="col-2"></div>
            </div>

            <div class="row"></div>

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ patient.pic.url }}" alt="Admin"
                                    class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>{{ patient.patient_name }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-4">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <line x1="16" y1="2" x2="16" y2="6"></line>
                                        <line x1="8" y1="2" x2="8" y2="6"></line>
                                        <line x1="3" y1="10" x2="21" y2="10"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'patient:bookings' %}">Appointments</a>
                                </h5>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <line x1="16" y1="2" x2="16" y2="6"></line>
                                        <line x1="8" y1="2" x2="8" y2="6"></line>
                                        <line x1="3" y1="10" x2="21" y2="10"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'patient:booking_history' %}">Bookings</a>
                                </h5>
                            </li>

                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                                        <path d="M7 11V7a5 5 0 0 1 9.9-1"></path>
                                    </svg> &ensp;
                                    <a href="{% url 'patient:chg-pwd' %}">Change Password</a>
                                </h5>
                            </li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-8">


                    <div class="card mb-3">
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Full Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" name="p_name"
                                            value="{{ patient.patient_name }}">
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Address</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" name="p_address"
                                            value="{{ patient.address }}">
                                    </div>
                                </div>


                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Age</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" readonly name="p_age" value="{{ patient.age }}">
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Gender</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" readonly name="p_gender"
                                            value="{{ patient.gender }}">
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Blood Group</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <select class="form-select mt-3 form-control"  name="blood_grp" id="p_bg" required>
                                            <option value="A+">A+</option>
                                            <option value="A-">A-</option>
                                            <option value="B+">B+</option>
                                            <option value="B-">B-</option>
                                            <option value="AB+">AB+</option>
                                            <option value="AB-">AB-</option>
                                            <option value="O+">O+</option>
                                            <option value="O-">O-</option>
                                        </select>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Phone</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" name="phone"
                                            value="{{ patient.phone }}">
                                    </div>
                                </div>

                                <hr>
                                <div class="row">
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-9 text-secondary">
                                         <input type="submit" class="btn btn-primary px-4"
                                                value="Save Changes">
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>

    </div>

</section>

{% endblock %}